name: bedrock
description: The Flutter plugin make app builds easier, providing some convenient features for building app for Android and iOS as the bedrock.
version: 0.2.1
repository: https://github.com/ChuNglyRic/bedrock

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # third party
  bedrock_platform_interface: ^0.1.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.1.5

flutter:
  plugin:
    platforms:
      android:
        package: com.chunglyric.bedrock
        pluginClass: BedrockPlugin
      ios:
        pluginClass: FLTBedrockPlugin
